services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ybooking_php
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
      - mailer
    command: sh -c "composer install --no-scripts && php -S 0.0.0.0:8000 -t public"

  database:
    image: mysql:8.0
    container_name: ybooking_db
    restart: always
    environment:
      MYSQL_DATABASE: eventDB
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

  mailer:
    image: axllent/mailpit
    container_name: ybooking_mailer
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database_data:
