services:
  - type: web
    name: miniprojet-event-reservation
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        value: "render-production-secret-change-me"
      - key: DATABASE_URL
        sync: false
      - key: MAILER_DSN
        value: "null://null"
      - key: MESSENGER_TRANSPORT_DSN
        value: "sync://"
      - key: DEFAULT_URI
        value: "https://miniprojet-event-reservation.onrender.com"
      - key: JWT_PASSPHRASE
        generateValue: true
      - key: RUN_MIGRATIONS
        value: "1"
